In [429]:
import os
import pandas as pd
import numpy as np

In [430]:
def get_data(df):
    df['Total time'] = df.sum(axis='columns', numeric_only=True)
    
    mapping = {df.columns[0]: "Vessels and activity", df.columns[1]: "units"}
    df.rename(columns=mapping, inplace=True)
    
    times_df = df.tail(-28).reset_index(drop=True) 
    
    split = times_df["Vessels and activity"].str.split(" ", n = 1, expand = True)
    times_df['vessel'] = split[0]
    times_df['else'] = split[1]
    
    split1 = times_df['else'].str.split(" ", n=1, expand=True)
    times_df['vessel_num'] = split1[0]
    times_df['activity1'] = split1[1]
    
    for index, row in times_df.iterrows():
        if len(row['vessel_num']) > 1:
            times_df.at[index, 'vessel_num'] = '1'
                        
    activities = {
        'at port': 'idle at port',
        'transit time': 'transit',
        'at sea': 'idle at sea',
        'idle at port': 'idle at port',
        'idle at sea': 'idle at sea',
        'time': 'transit'
    }
    times_df['activity'] = times_df['activity1'].map(activities)
    
    times_df.drop(['activity1', 'else'], axis=1, inplace=True)
    
    return times_df

In [450]:
def group(s, df):
    savepath = 'results/' + s + 'pg.csv'
    
    df_grouped = df.groupby(['vessel', 'activity'], as_index=True, group_keys=False).sum(numeric_only=True)['Total time']
    df_grouped = pd.DataFrame(df_grouped)
    
    df_grouped.to_csv(savepath)
    new_grouped = pd.read_csv(savepath)
    
    for index, row in new_grouped.iterrows():
        if row['activity'] == 'transit':
            tt = row['Total time']
            new_transit = 0.9*tt
            maneuvering = 0.1*tt
            new_grouped.loc[len(new_grouped.index)] = [row['vessel'], 'maneuvering', maneuvering]
            new_grouped.at[index, 'Total time'] = new_transit
            
    return new_grouped

In [469]:
def calc_emissions(df):
    efs = {
      ('aht', 'transit'): 11.48620032,
      ('aht', 'maneuvering'): 6.93707868,
      ('aht', 'idle at port'): 1.16877936,
      ('aht', 'idle at sea'): 0.58438968,
      ('cable', 'transit'): 4.148689675,
      ('cable', 'maneuvering'): 2.555691113,
      ('cable', 'idle at port'): 0.444414438,
      ('cable', 'idle at sea'): 0.222207219,
      ('dsv', 'transit'): 1.111751032,
      ('dsv', 'maneuvering'): 0.432559932,
      ('dsv', 'idle at port'): 0.00695702,
      ('dsv', 'idle at sea'): 0.00347851,
      ('sov', 'transit'): 4.501852376,
      ('sov', 'maneuvering'): 3.369358524,
      ('sov', 'idle at port'): 0.747183948,
      ('sov', 'idle at sea'): 0.373591974,
      ('tug', 'transit'): 11.48620032,
      ('tug', 'maneuvering'): 6.93707868,
      ('tug', 'idle at port'): 1.16877936,
      ('tug', 'idle at sea'): 0.58438968
    }

    df['Emissions_factor'] = df[['vessel', 'activity']].apply(tuple, axis=1).map(efs)
    df['Emissions'] = df['Total time'] * df['Emissions_factor']
    
    df.sort_values('vessel', ascending=True, inplace=True)
    
    return df

In [470]:
output_file = 'WCports_results_23Mar.xlsx'
ctv_scenarios = ['WCports_test_ctv6', 'WCports_test_ctv8']
sov_scenarios = ['WCports_test_sov6']

In [471]:
## calculate emissions for CTV scenarios. one project, one year
for s in ctv_scenarios:
    ctv_df_raw = pd.read_excel(output_file, sheet_name=s)
    ctv_df = get_data(ctv_df_raw)
    ctv_grouped = group(s, ctv_df)
    ctv_grouped = calc_emissions(ctv_grouped)

In [472]:
## calculate emissions for SOV scenarios. one project, one year
for s in sov_scenarios:
    sov_df_raw = pd.read_excel(output_file, sheet_name=s)
    sov_df = get_data(sov_df_raw)
    sov_grouped = pd.DataFrame(group(s, sov_df))
    sov_grouped = calc_emissions(sov_grouped)

In [473]:
sov_grouped

   vessel      activity    Total time  Emissions_factor      Emissions
0     aht  idle at port  33869.436149          1.168779   39585.897906
1     aht   idle at sea   6572.296713          0.584390    3840.782373
2     aht       transit  22875.606159         11.486200  262753.794787
15    aht   maneuvering   2541.734018          6.937079   17632.208864
3   cable  idle at port  38604.911120          0.444414   17156.579880
4   cable   idle at sea  13726.900991          0.222207    3050.216495
5   cable       transit  20119.118653          4.148690   83467.979827
16  cable   maneuvering   2235.457628          2.555691    5713.139194
6     dsv  idle at port  20134.020033          0.006957     140.072780
7     dsv   idle at sea   7855.046060          0.003479      27.323856
8     dsv       transit   8877.785690          1.111751    9869.887403
17    dsv   maneuvering    986.420632          0.432560     426.686042
9     sov  idle at port  47749.532752          0.747184   35677.684397
11    sov       transit   2615.084790          4.501852   11772.725673
10    sov   idle at sea  15261.441069          0.373592    5701.551895
18    sov   maneuvering    290.564977          3.369359     979.017581
13    tug   idle at sea   4592.246921          0.584390    2683.661709
14    tug       transit   2053.003515         11.486200   23581.209635
12    tug  idle at port    724.656491          1.168779     846.963549
19    tug   maneuvering    228.111502          6.937079    1582.427435